---

- name: Main configuration file
  template:
    src: collectd.conf.j2
    dest: /etc/collectd.conf
    backup: no
  notify:
    - restart collectd

- name: Plugin configuration file(s)
  template:
    src: "plugins/{{ item }}.conf.j2"
    dest: "{{ collectd_includes_path }}/{{ item }}.conf"
  with_items: collectd_plugins
  notify:
    - restart collectd

- name: Make collectd_t a permissive SELinux domain (required for most plugins)
  selinux_permissive:
    domain: collectd_t
    permissive: yes
  when: collectd_selinux_permissive and ansible_selinux.status != 'disabled'
