---
- name: Add EPEL repository
  package:
    name: epel-release
    state: latest
  tags:
    - skip_ansible_lint

- name: Install packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - "collectd"
    - "{{ collectd_extra_packages }}"
  notify:
    - restart collectd
  tags:
    - skip_ansible_lint
